- .travis.yml
- .vscode/settings.json
> [simple] Adding Travis CI

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
For managing our project well with Github, it would be better to have issue and pull request templates.
Issue templates are mostly based on Github default templates. I wrote the pull request template by myself.
> Create issue and pull request templates

- backend/papersfeed/apis.py
- backend/papersfeed/tests/tests_user.py
- backend/papersfeed/utils/users/utils.py
- backend/papersfeed/views.py
Related Issue: #58 #63 
it resolves #58 and resolves #63 
(select_session in backend/papersfeed/utils/users/utils.py)
(select_me in backend/papersfeed/utils/users/utils.py)
My codes...
> Return current user from backend(Issue #58, #63)

- backend/papersfeed/tests/tests_user.py
- backend/papersfeed/utils/users/utils.py
Related Issue: #66
resolves #66 
Not a big change on this pull request.
Modify the backend function 'update_user' in '/backend/papersfeed/utils/users/users.py' to handle change on user description.
If needed, please refer to user API at https://github.com/swsnu/swpp2019-team3/pull/38
My codes...
> modify update_user

- backend/papersfeed/constants.py
- backend/papersfeed/tests/tests.py
- backend/papersfeed/views.py
Related Issue: #60 
It resolves #60 
constants의 Api Error Code에 "INVALID_JSON = 520  # json.loads 에러" 추가
views.py의 api_entry함수에서 error handling 수정
> except ValueError를 추가하여 json.loads 실패 시 520 return
tests.py에 json.loads를 실패하는 API 테스트케이스를 추가
My codes...
> json.loads Error Handling

- backend/PapersFeed_backend/settings.py
- backend/papersfeed/tests/tests_user.py
- backend/papersfeed/urls.py
- backend/papersfeed/views.py
- frontend/src/index.js
Reverts swsnu/swpp2019-team3#84
There was an unexpected error because of difference between #75 and #84. We merged two PRs after checking, but mixed logics on the master branch generated an unexpected trivial test fail. So we'll fix it after reverting the last PR.
> Revert "csrf_setting"

- backend/papersfeed/utils/papers/abstract_analysis.py
- backend/papersfeed/utils/papers/utils.py
- frontend/src/components/Header/Header.js
- frontend/src/components/Header/Header.test.js
Related Issue: #73 
Text Analytics API & arXiv API error handling.
I made pressing 'enter' for search disabled. Please uncomment related codes when remaining problems mentioned in #107 PR.
My codes...
> [minor] Error handling when searching papers

- backend/papersfeed/tests/tests_user.py
- backend/papersfeed/views.py
- frontend/src/components/Header/Header.css
- frontend/src/components/Header/Header.js
- frontend/src/containers/Main/Main.css
- frontend/src/containers/Main/Main.js
Related Issue: #116 
This PR will resolve #116 issue.
Dropdown menus will be in front of other components, although I can't check it directly because those symptoms only occur in the [deployed site](http://52.141.45.145/).
- For now, we don't have subscription and recommendation system yet. Not to make users confused, I removed stub data from Main Page.
- Also, until the problem which I mentioned in #107 PR and #118 issue is resolved, we should inform users that they can search only with the 'Search' button. So I added the message to the placeholder of the search bar.
- As mentioned in the comment of #83 issue, 403 error is always raised in some environment and **also in the deployed site**. So I made APIs exempted about CSRF, for now.
My codes...
> frontend works for temporary situations & csrf_exempt

- backend/papersfeed/apis.py
- backend/papersfeed/constants.py
- backend/papersfeed/tests/papers/tests_paper.py
- backend/papersfeed/tests/tests_recommendation.py
- backend/papersfeed/utils/recommendations/utils.py
- backend/papersfeed/views.py
- frontend/src/components/Reply/Reply.js
- frontend/src/components/Reply/Reply.test.js
- frontend/src/containers/Review/ReviewDetail/ReviewDetail.js
Related Issue: #87 
1. Add get_user_all api
2. Add get_paper_all api
3. Add get_recommendation api
4. Change get_user_action api so that ml server could get new papers and user list
1. Change date format of review and reply
My codes...
> Recommendation Util

- backend/papersfeed/utils/recommendations/utils.py
Related Issue: #87 
1. Fix get/user/all api
My codes...
> Fix get/user/all api

- backend/papersfeed/apis.py
- backend/papersfeed/constants.py
- backend/papersfeed/tests/tests_user.py
- backend/papersfeed/utils/users/utils.py
Related Issue: #145 
It resolves #145 
- GET /api/user/following/collection
> (following하고 있는 user 중 collection_id를 받아 collection에 안들어있는 사람 가져오는 API)
- GET /api/user/search/collection
> (전체 user 중 text와 collection_id를 받아 collection에 안들어가있는 사람 가져오는 API)
My codes...
> Get users for invite user to collection

- backend/papersfeed/apis.py
- backend/papersfeed/tests/tests_collection.py
- backend/papersfeed/utils/collections/utils.py
Related Issue: #151 
It resolves #151 
GET /api/collection/user/shared
해당 유저의 collection 중 소속 멤버가 2명 이상인 collection만 가져오는 API
My codes...
> Get Shared Collection

- frontend/src/containers/Init/Init.js
- frontend/src/containers/Init/Init.test.js
Related Issue:
Fix
My codes...
> [minor] Unchecking problems on Init

- frontend/src/components/Modal/CreateNewCollectionModal/CreateNewCollectionModal.js
- frontend/src/components/Photo/PhotoCheckBox/PhotoCheckBox.css
- frontend/src/components/Photo/PhotoCheckBox/PhotoCheckBox.js
- frontend/src/components/User/UserEntry/UserEntry.js
Related Issue: #205 
resolves #205 
The checkbox will now look normal as before.
Fixed some checkboxes to change the value of them when the associated label is clicked.
My codes...
> fix checkbox

- backend/papersfeed/apis.py
- backend/papersfeed/tests/tests_user.py
- backend/papersfeed/urls.py
- backend/papersfeed/utils/base_utils.py
- backend/papersfeed/views.py
- frontend/src/store/actions/review/review.js
Related Issue: #83 
This PR will resolve #83 issue.
Now, our service can use CSRF setting(hopefully). Please refer to https://github.com/swsnu/swppfall2019/issues/212 for more information.
Implement a view wrapper for `GET /api/session` and `POST /api/user`.
My codes...
> CSRF setting

- backend/papersfeed/apis.py
Related Issue: #138 
1. add csrf exempt
My codes...
> csrf exempt

- frontend/src/components/Collection/CollectionCard/CollectionCard.js
Related Issue: #133 
1. Edit Card Reply Button
My codes...
> CollectionCard Reply Button Fix

- frontend/src/components/Collection/CollectionCard/CollectionCard.js
- frontend/src/containers/Collection/CollectionDetail/CollectionDetail.js
- frontend/src/containers/Collection/CollectionDetail/CollectionDetail.test.js
Related Issue: #133 
1. Collection Card Reply Button
2. Alert on Collection Detail Page
My codes...
> Collection Card Reply Button Fix & Alert on Collection Detail Page

- requirements.txt
Related Issue: https://github.com/swsnu/swpp2019-team3/network/alert/requirements.txt/Django/open
Upgraded Django to 2.2.9 version to resolve security issues.
My codes...
> upgrade Django to 2.2.9

- requirements.txt
Related Issue: https://github.com/swsnu/swpp2019-team3/network/alert/requirements.txt/django/open
Upgraded Django to 2.2.10 version to resolve security issues.
My codes...
> upgrade Django to 2.2.10
